apiVersion: v1
kind: Template
metadata:
  name: signalalertsapi
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:latest
      runPolicy: Serial
      source:
        git:
          uri: ${GIT_REMOTE_URI}
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: openjdk-11-rhel7:latest
        type: Source
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    data:
      install-signal-cli.sh: |-
        #!/bin/bash
        if [ ! -d "$SIGNAL_CLI_PATH/signal-cli-${SIGNAL_CLI_VERSION}" ]; then
          curl -Lo $SIGNAL_CLI_PATH/signal-cli-"${SIGNAL_CLI_VERSION}".tar.gz https://github.com/AsamK/signal-cli/releases/download/v"${SIGNAL_CLI_VERSION}"/signal-cli-"${SIGNAL_CLI_VERSION}".tar.gz
          tar xf $SIGNAL_CLI_PATH/signal-cli-"${SIGNAL_CLI_VERSION}".tar.gz -C $SIGNAL_CLI_PATH
        fi
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      replicas: 1
      selector:
        app: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          name: ${NAME}
          labels:
            app: ${NAME}
        spec:
          initContainers:
            - name: ${NAME}-init
              image: " "
              command: ['sh', '-c', '/init/install-signal-cli.sh']
              env:
                - name: SIGNAL_CLI_PATH
                  value: ${SIGNAL_CLI_PATH}
              volumeMounts:
                - name: ${NAME}-init
                  mountPath: /init
                - name: signaldest
                  mountPath: ${SIGNAL_CLI_PATH}
          containers:
            - name: ${NAME}
              image: " "
              env:
                - name: SENDER_PHONENUMBER
                  value: ${SENDER_PHONENUMBER}
                - name: RECIPIENT_PHONENUMBER
                  value: ${RECIPIENT_PHONENUMBER}
                - name: SIGNAL_CLI
                  value: ${SIGNAL_CLI_PATH}/signal-cli-${SIGNAL_CLI_VERSION}/bin/signal-cli
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: signaldest
                  mountPath: ${SIGNAL_CLI_PATH}
          volumes:
            - configMap:
                defaultMode: 0777
                name: ${NAME}
              name: ${NAME}-init
            - emptyDir: {}
              name: signaldest
      triggers:
        - type: configChange
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - ${NAME}
              - ${NAME}-init
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${NAME}
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}

parameters:
  - name: NAME
    value: signalalertsapi
  - name: GIT_REMOTE_URI
    value: https://github.com/Sharelison/signalalerts-api.git
  - name: SENDER_PHONENUMBER
    value: "+3166666666"
  - name: RECIPIENT_PHONENUMBER
    value: "+3166666666"
  - name: SIGNAL_CLI_PATH
    value: /tmp
  - name: SIGNAL_CLI_VERSION
    value: 0.6.7
